### ISSUE TITLE
Filter Support for Two or More Substrings

### ISSUE THREAD

**Issue by wes8ty** [pamburus/hl#87]
Is the following supported by having two filtered substrings?
```
./hl final.log -f message~=status -f container_name=datadog
```
I have it working if I only use one filter (each tested correctly by themselves) but when I combine both, the output is nothing. Trying to get logs for a container name with the word `status` in the message field.

**Comment by pamburus** [comment]
Yes, it is supported. It combines those filters using "AND" operator.
So, only messages that meet both filter conditions are shown.

Probably you want to combine them using "OR" operator.
Currently it is possible to specify multiple values to match for a single field using regular expression filter.
But unfortunately there is no way to achieve that for 2 different fields.

I'll think how to add this feature.

**Comment by wes8ty** [comment]
I actually wanted the AND operator when doing this. However, when I try to filter on MESSAGE and another json name it does not show any results.

Example:

```
./hl final.log -f message~=flush -f container_name=supervisor
```

``` json
{"_SYSTEMD_UNIT": "supervisor.service", "PRIORITY": "7", "__REALTIME_TIMESTAMP": "1696533827415972", "__MONOTONIC_TIMESTAMP": "772230678178", "MESSAGE": "[\u001b[35mdebug\u001b[39m]   Attempting container log timestamp flush...", "CONTAINER_ID": "3b3822138837", "SYSLOG_IDENTIFIER": "3b3822138837", "CONTAINER_NAME": "supervisor"}
```

**Comment by pamburus** [comment]
Hmm. It's strange. Exactly this commands works as expected in my environment - it shows this message.
Could you share `hl` version, your config file (~/.config/hl/config.yaml) and environment variables `env | grep '^HL_'`?

**Comment by wes8ty** [comment]
```
hl 0.20.0-beta.14.7.1
```

config
``` yaml
# Time format, see https://man7.org/linux/man-pages/man1/date.1.html for details.
time-format: "%b %d %I:%M:%S.%3N %p %Z"

# Time zone name, see column "TZ identifier" at
# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones page.
time-zone: America/New_York

# Settings for fields processing.
fields:
  # Configuration of the predefined set of fields.
  predefined:
    time:
      names:
        [
          ts,
          TS,
          time,
          TIME,
          Time,
          Timestamp,
          _SOURCE_REALTIME_TIMESTAMP,
          __REALTIME_TIMESTAMP,
        ]
    logger:
      names: [logger, LOGGER, Logger]
    level:
      variants:
        - names: [level, LEVEL, Level]
          values:
            debug: [debug, Debug]
            info: [info, information, Information]
            warning: [warning, Warning, warn]
            error: [error, Error, err, fatal, critical, panic]
        - names: [PRIORITY]
          values:
            debug: [7]
            info: [6]
            warning: [5, 4]
            error: [3, 2, 1]
    message:
      names: [msg, message, MESSAGE, Message]
    caller:
      names: [caller, CALLER, Caller]
  # List of wildcard field names to ignore.
  ignore: ["_*"]
  # List of exact field names to hide.
  hide:
    [
      "CONTAINER-ID",
      "CONTAINER-ID-FULL",
      "IMAGE-NAME",
      "CONTAINER-TAG",
      "SYSLOG-IDENTIFIER",
    ]

# Formatting settings.
formatting:
  punctuation:
    logger-name-separator: ":"
    field-key-value-separator: "="
    string-opening-quote: "'"
    string-closing-quote: "'"
    source-location-separator: "@ "
    hidden-fields-indicator: " ..."
    level-left-separator: "|"
    level-right-separator: "|"
    input-number-prefix: "#"
    input-number-left-separator: ""
    input-number-right-separator: " | "
    input-name-left-separator: ""
    input-name-right-separator: " | "
    input-name-clipping: "..."
    input-name-common-part: "..."

# Number of processing threads, configured automatically based on CPU count if not specified.
concurrency: ~

# Currently selected theme.
theme: universal
```
