### ISSUE TITLE
Different colors for boolean `true` and `false`

### ISSUE THREAD

**Issue by zx8** [pamburus/hl#944]
It would be neat to be able to choose different colors for boolean `true`/`false` (e.g. green/red).

Perhaps something along the lines of:

```yaml
elements:
  # Default, if `boolean_*` is not specified
  boolean:
    foreground: yellow
  # Takes precedence over `boolean`
  boolean_true:
    foreground: green
  # Takes precedence over `boolean`
  boolean_false:
    foreground: red
```

What do you think?
