### ISSUE TITLE
Custom predefined field names not recognized when using multi-word names

### ISSUE THREAD

**Issue by tvhung83** [pamburus/hl#945]
Hi, thank you for this great tool!

I'm encountering an issue when trying to add custom predefined field names. Here's an example of my configuration:
```yaml
# Settings for fields processing.
fields:
  # Configuration of the predefined set of fields.
  predefined:
    // ...
    logger:
      names: ["logger-name", "logger", "LOGGER", "Logger"]
    caller:
      names: ["thread-name", "caller", "CALLER", "Caller"]
```
I added `"logger-name"` under `logger` and `"thread-name"` under `caller`, but these multi-word names are not being recognized during processing. Interestingly, single-word field names like `"method"` work as expected.

Is there a limitation with multi-word field names, or am I missing something in the configuration?

Thanks again for your work on this project!
